import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppNavBar from "@/components/Navigation";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark bg-background text-foreground h-screen w-screen">
        <AppNavBar />
        <div className="overflow-y-scroll flex flex-1 flex-col h-[calc(100vh-68px)]">
          <div className="flex flex-col flex-1">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
